### ISSUE TITLE
Unable to utilise the discovery service

### ISSUE THREAD

**Issue by jmclear** [watson-developer-cloud/visual-recognition-with-discovery-coreml#13]
I have the app installed successfully on my phone. It has classified the image correctly and then at the bottom it says 
"Retrieving more information on thunderbolt male...."
It's been stuck on this for 10+ minutes.

Any tips?

Thanks
Jack

**Comment by jpmmtrader** [comment]
I have a similar result. The error logs shows errors as follows even without using the app. 

> 2018-07-03 22:02:43.617418+1000 Core ML Vision Discovery[3454:2684117] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2018-07-03 22:02:43.617643+1000 Core ML Vision Discovery[3454:2684117] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

**Comment by jpmmtrader** [comment]
I have the same issue, I inserted a print statement immediately after the `queryResponse in` statement  `queryResponse in
            print("%%%%%%%%%%%%%%%%%%%     queryResponse.passages",queryResponse.passages)
            print("%%%%%%%%%%%%%%%%%%%     queryResponse.results",queryResponse.results)` to check what results were coming back and found that `queryResponse.passages` is nil, but `queryResponse.response` pulls back the data, so now I know the Discivery service is all working and returning the results, the error is in parsing the data with the QueryPassge method. I haven't figured out how to parse the data without a lot of string parsing. The passageTextmethod shown below looks like an elegant way to parse so I'll keep looking into that

`text = passages[0].passageText ?? "No Discovery results found."`

**Comment by jpmmtrader** [comment]
THANK YOU....works great now
