### ISSUE TITLE
Not able to run sample application on device and simulator both

### ISSUE THREAD

**Issue by VireshS** [watson-developer-cloud/visual-recognition-with-discovery-coreml#6]
I followed the step mentioned and linked the compiled framework together with obtaining and updating the required keys from Watson studio project. However I am not able to run the application on Device and simulator both. It builds successfully but doesn't run. When I run the app, it crashes with below error:
```
dyld: Library not loaded: @rpath/DiscoveryV1.framework/DiscoveryV1
  Referenced from: /var/containers/Bundle/Application/F03F84A7-B789-49C6-A8A7-168583B5B2C7/Core ML Vision Discovery.app/Core ML Vision Discovery
  Reason: image not found
(lldb)
```

Tried cleaning the build and removing derive data folder as well but didn't work. Is there anything I missed?

**Comment by mediumTaj** [comment]
It looks like the Discovery framework has not been set. Please follow these steps to embed the Discovery framework

1. In Xcode, use the Project Navigator to select the Core ML Vision Discovery.xcodeproj project.
1. In the General settings tab, scroll down to Embedded Binaries and click the + icon.
1. Click Add Other, navigate to the Carthage/Build/iOS directory, and select DiscoveryV1.framework.

**Comment by VireshS** [comment]
Thanks, It worked. It will be good if you can add these locations in project itself rather than adding it again or update the steps to include this framework as well.
Great sample though!

**Comment by mediumTaj** [comment]
Yes, this was planned right before the release. After seeing your issue I created this issue to track the work https://github.com/watson-developer-cloud/visual-recognition-with-discovery-coreml/issues/7

**Comment by VireshS** [comment]
Great, I have changes ready. I can raise a PR for the same. I can do it tomorrow.
